-- ============================================================================
-- VALENSZO SQL MIGRATION: ADD BRAND COLUMN AND POPULATE FROM EXCEL
-- Run this in your Supabase SQL Editor (Dashboard -> SQL Editor -> New Query -> Run)
-- ============================================================================

-- 1. Add brand column to products table
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS brand TEXT;

-- 2. Populate brand for all 345 catalog perfumes from Excel
UPDATE public.products SET brand = 'Bvlgari' WHERE (specs->>'catalogNo')::int = 6 AND category = 'Men';
UPDATE public.products SET brand = 'Bvlgari' WHERE (specs->>'catalogNo')::int = 53 AND category = 'Men';
UPDATE public.products SET brand = 'Bvlgari' WHERE (specs->>'catalogNo')::int = 89 AND category = 'Men';
UPDATE public.products SET brand = 'Chanel' WHERE (specs->>'catalogNo')::int = 74 AND category = 'Men';
UPDATE public.products SET brand = 'Clinique' WHERE (specs->>'catalogNo')::int = 5 AND category = 'Men';
UPDATE public.products SET brand = 'Davidoff' WHERE (specs->>'catalogNo')::int = 33 AND category = 'Men';
UPDATE public.products SET brand = 'Davidoff' WHERE (specs->>'catalogNo')::int = 75 AND category = 'Men';
UPDATE public.products SET brand = 'Dunhill' WHERE (specs->>'catalogNo')::int = 13 AND category = 'Men';
UPDATE public.products SET brand = 'Giorgio Armani' WHERE (specs->>'catalogNo')::int = 2 AND category = 'Men';
UPDATE public.products SET brand = 'Jaguar' WHERE (specs->>'catalogNo')::int = 14 AND category = 'Men';
UPDATE public.products SET brand = 'Lattafa' WHERE (specs->>'catalogNo')::int = 108 AND category = 'Men';
UPDATE public.products SET brand = 'Montblanc' WHERE (specs->>'catalogNo')::int = 59 AND category = 'Men';
UPDATE public.products SET brand = 'Rabanne' WHERE (specs->>'catalogNo')::int = 17 AND category = 'Men';
UPDATE public.products SET brand = 'Valentino' WHERE (specs->>'catalogNo')::int = 115 AND category = 'Men';
UPDATE public.products SET brand = 'Valentino' WHERE (specs->>'catalogNo')::int = 117 AND category = 'Men';
UPDATE public.products SET brand = 'Versace' WHERE (specs->>'catalogNo')::int = 73 AND category = 'Men';
UPDATE public.products SET brand = 'Bvlgari' WHERE (specs->>'catalogNo')::int = 10 AND category = 'Men';
UPDATE public.products SET brand = 'Calvin Klein' WHERE (specs->>'catalogNo')::int = 30 AND category = 'Men';
UPDATE public.products SET brand = 'Giorgio Armani' WHERE (specs->>'catalogNo')::int = 99 AND category = 'Men';
UPDATE public.products SET brand = 'Louis Vuitton' WHERE (specs->>'catalogNo')::int = 92 AND category = 'Men';
UPDATE public.products SET brand = 'Louis Vuitton' WHERE (specs->>'catalogNo')::int = 105 AND category = 'Men';
UPDATE public.products SET brand = 'Louis Vuitton' WHERE (specs->>'catalogNo')::int = 104 AND category = 'Men';
UPDATE public.products SET brand = 'Maison Margiela' WHERE (specs->>'catalogNo')::int = 114 AND category = 'Men';
UPDATE public.products SET brand = 'Nishane' WHERE (specs->>'catalogNo')::int = 103 AND category = 'Men';
UPDATE public.products SET brand = 'Yves Saint Laurent' WHERE (specs->>'catalogNo')::int = 98 AND category = 'Men';
UPDATE public.products SET brand = 'Azzaro' WHERE (specs->>'catalogNo')::int = 62 AND category = 'Men';
UPDATE public.products SET brand = 'Burberry' WHERE (specs->>'catalogNo')::int = 57 AND category = 'Men';
UPDATE public.products SET brand = 'Bvlgari' WHERE (specs->>'catalogNo')::int = 65 AND category = 'Men';
UPDATE public.products SET brand = 'Calvin Klein' WHERE (specs->>'catalogNo')::int = 3 AND category = 'Men';
UPDATE public.products SET brand = 'Carolina Herrera' WHERE (specs->>'catalogNo')::int = 52 AND category = 'Men';
UPDATE public.products SET brand = 'Chanel' WHERE (specs->>'catalogNo')::int = 49 AND category = 'Men';
UPDATE public.products SET brand = 'Coach' WHERE (specs->>'catalogNo')::int = 88 AND category = 'Men';
UPDATE public.products SET brand = 'Davidoff' WHERE (specs->>'catalogNo')::int = 32 AND category = 'Men';
UPDATE public.products SET brand = 'Dolce & Gabbana' WHERE (specs->>'catalogNo')::int = 35 AND category = 'Men';
UPDATE public.products SET brand = 'Giorgio Armani' WHERE (specs->>'catalogNo')::int = 77 AND category = 'Men';
UPDATE public.products SET brand = 'Gucci' WHERE (specs->>'catalogNo')::int = 26 AND category = 'Men';
UPDATE public.products SET brand = 'Guy Laroche' WHERE (specs->>'catalogNo')::int = 67 AND category = 'Men';
UPDATE public.products SET brand = 'Hugo Boss' WHERE (specs->>'catalogNo')::int = 60 AND category = 'Men';
UPDATE public.products SET brand = 'Hugo Boss' WHERE (specs->>'catalogNo')::int = 18 AND category = 'Men';
UPDATE public.products SET brand = 'Hugo Boss' WHERE (specs->>'catalogNo')::int = 9 AND category = 'Men';
UPDATE public.products SET brand = 'Jaguar' WHERE (specs->>'catalogNo')::int = 15 AND category = 'Men';
UPDATE public.products SET brand = 'Jean Paul Gaultier' WHERE (specs->>'catalogNo')::int = 31 AND category = 'Men';
UPDATE public.products SET brand = 'Jimmy Choo' WHERE (specs->>'catalogNo')::int = 7 AND category = 'Men';
UPDATE public.products SET brand = 'John Varvatos' WHERE (specs->>'catalogNo')::int = 19 AND category = 'Men';
UPDATE public.products SET brand = 'Montblanc' WHERE (specs->>'catalogNo')::int = 51 AND category = 'Men';
UPDATE public.products SET brand = 'Montblanc' WHERE (specs->>'catalogNo')::int = 34 AND category = 'Men';
UPDATE public.products SET brand = 'Montblanc' WHERE (specs->>'catalogNo')::int = 55 AND category = 'Men';
UPDATE public.products SET brand = 'Rabanne' WHERE (specs->>'catalogNo')::int = 116 AND category = 'Men';
UPDATE public.products SET brand = 'Rabanne' WHERE (specs->>'catalogNo')::int = 29 AND category = 'Men';
UPDATE public.products SET brand = 'Ralph Lauren' WHERE (specs->>'catalogNo')::int = 39 AND category = 'Men';
UPDATE public.products SET brand = 'Ralph Lauren' WHERE (specs->>'catalogNo')::int = 27 AND category = 'Men';
UPDATE public.products SET brand = 'Tom Ford' WHERE (specs->>'catalogNo')::int = 69 AND category = 'Men';
UPDATE public.products SET brand = 'Tommy Hilfiger' WHERE (specs->>'catalogNo')::int = 41 AND category = 'Men';
UPDATE public.products SET brand = 'Versace' WHERE (specs->>'catalogNo')::int = 28 AND category = 'Men';
UPDATE public.products SET brand = 'Yves Saint Laurent' WHERE (specs->>'catalogNo')::int = 91 AND category = 'Men';
UPDATE public.products SET brand = 'Calvin Klein' WHERE (specs->>'catalogNo')::int = 23 AND category = 'Men';
UPDATE public.products SET brand = 'Hugo Boss' WHERE (specs->>'catalogNo')::int = 50 AND category = 'Men';
UPDATE public.products SET brand = 'Montblanc' WHERE (specs->>'catalogNo')::int = 66 AND category = 'Men';
UPDATE public.products SET brand = 'Amouage' WHERE (specs->>'catalogNo')::int = 107 AND category = 'Men';
UPDATE public.products SET brand = 'Dunhill' WHERE (specs->>'catalogNo')::int = 8 AND category = 'Men';
UPDATE public.products SET brand = 'Ferrari' WHERE (specs->>'catalogNo')::int = 42 AND category = 'Men';
UPDATE public.products SET brand = 'Hugo Boss' WHERE (specs->>'catalogNo')::int = 4 AND category = 'Men';
UPDATE public.products SET brand = 'Hugo Boss' WHERE (specs->>'catalogNo')::int = 11 AND category = 'Men';
UPDATE public.products SET brand = 'Tom Ford' WHERE (specs->>'catalogNo')::int = 81 AND category = 'Men';
UPDATE public.products SET brand = 'Hugo Boss' WHERE (specs->>'catalogNo')::int = 64 AND category = 'Men';
UPDATE public.products SET brand = 'Dunhill' WHERE (specs->>'catalogNo')::int = 45 AND category = 'Men';
UPDATE public.products SET brand = 'Giorgio Armani' WHERE (specs->>'catalogNo')::int = 93 AND category = 'Men';
UPDATE public.products SET brand = 'Jean Paul Gaultier' WHERE (specs->>'catalogNo')::int = 16 AND category = 'Men';
UPDATE public.products SET brand = 'Memo Paris' WHERE (specs->>'catalogNo')::int = 113 AND category = 'Men';
UPDATE public.products SET brand = 'Rabanne' WHERE (specs->>'catalogNo')::int = 109 AND category = 'Men';
UPDATE public.products SET brand = 'Tom Ford' WHERE (specs->>'catalogNo')::int = 80 AND category = 'Men';
UPDATE public.products SET brand = 'Versace' WHERE (specs->>'catalogNo')::int = 97 AND category = 'Men';
UPDATE public.products SET brand = 'Azzaro' WHERE (specs->>'catalogNo')::int = 90 AND category = 'Men';
UPDATE public.products SET brand = 'Carolina Herrera' WHERE (specs->>'catalogNo')::int = 47 AND category = 'Men';
UPDATE public.products SET brand = 'Carolina Herrera' WHERE (specs->>'catalogNo')::int = 84 AND category = 'Men';
UPDATE public.products SET brand = 'Dior' WHERE (specs->>'catalogNo')::int = 63 AND category = 'Men';
UPDATE public.products SET brand = 'Dior' WHERE (specs->>'catalogNo')::int = 86 AND category = 'Men';
UPDATE public.products SET brand = 'Dunhill' WHERE (specs->>'catalogNo')::int = 102 AND category = 'Men';
UPDATE public.products SET brand = 'Hugo Boss' WHERE (specs->>'catalogNo')::int = 112 AND category = 'Men';
UPDATE public.products SET brand = 'Jean Paul Gaultier' WHERE (specs->>'catalogNo')::int = 100 AND category = 'Men';
UPDATE public.products SET brand = 'Maison Francis Kurkdjian' WHERE (specs->>'catalogNo')::int = 68 AND category = 'Men';
UPDATE public.products SET brand = 'Prada' WHERE (specs->>'catalogNo')::int = 38 AND category = 'Men';
UPDATE public.products SET brand = 'Gucci' WHERE (specs->>'catalogNo')::int = 82 AND category = 'Men';
UPDATE public.products SET brand = 'Rabanne' WHERE (specs->>'catalogNo')::int = 110 AND category = 'Men';
UPDATE public.products SET brand = 'Ralph Lauren' WHERE (specs->>'catalogNo')::int = 40 AND category = 'Men';
UPDATE public.products SET brand = 'Creed' WHERE (specs->>'catalogNo')::int = 12 AND category = 'Men';
UPDATE public.products SET brand = 'Gucci' WHERE (specs->>'catalogNo')::int = 71 AND category = 'Men';
UPDATE public.products SET brand = 'Hermes' WHERE (specs->>'catalogNo')::int = 46 AND category = 'Men';
UPDATE public.products SET brand = 'David Beckham' WHERE (specs->>'catalogNo')::int = 43 AND category = 'Men';
UPDATE public.products SET brand = 'Dunhill' WHERE (specs->>'catalogNo')::int = 36 AND category = 'Men';
UPDATE public.products SET brand = 'Le Labo' WHERE (specs->>'catalogNo')::int = 95 AND category = 'Men';
UPDATE public.products SET brand = 'Carolina Herrera' WHERE (specs->>'catalogNo')::int = 1 AND category = 'Men';
UPDATE public.products SET brand = 'Diesel' WHERE (specs->>'catalogNo')::int = 61 AND category = 'Men';
UPDATE public.products SET brand = 'Dior' WHERE (specs->>'catalogNo')::int = 24 AND category = 'Men';
UPDATE public.products SET brand = 'Etienne Aigner' WHERE (specs->>'catalogNo')::int = 37 AND category = 'Men';
UPDATE public.products SET brand = 'Giorgio Armani' WHERE (specs->>'catalogNo')::int = 54 AND category = 'Men';
UPDATE public.products SET brand = 'Giorgio Armani' WHERE (specs->>'catalogNo')::int = 76 AND category = 'Men';
UPDATE public.products SET brand = 'Jean Paul Gaultier' WHERE (specs->>'catalogNo')::int = 101 AND category = 'Men';
UPDATE public.products SET brand = 'Lattafa' WHERE (specs->>'catalogNo')::int = 106 AND category = 'Men';
UPDATE public.products SET brand = 'Montblanc' WHERE (specs->>'catalogNo')::int = 22 AND category = 'Men';
UPDATE public.products SET brand = 'Rabanne' WHERE (specs->>'catalogNo')::int = 25 AND category = 'Men';
UPDATE public.products SET brand = 'Rabanne' WHERE (specs->>'catalogNo')::int = 44 AND category = 'Men';
UPDATE public.products SET brand = 'Tom Ford' WHERE (specs->>'catalogNo')::int = 85 AND category = 'Men';
UPDATE public.products SET brand = 'Tom Ford' WHERE (specs->>'catalogNo')::int = 20 AND category = 'Men';
UPDATE public.products SET brand = 'Tom Ford' WHERE (specs->>'catalogNo')::int = 83 AND category = 'Men';
UPDATE public.products SET brand = 'Viktor&Rolf' WHERE (specs->>'catalogNo')::int = 72 AND category = 'Men';
UPDATE public.products SET brand = 'Lattafa' WHERE (specs->>'catalogNo')::int = 96 AND category = 'Men';
UPDATE public.products SET brand = 'Tom Ford' WHERE (specs->>'catalogNo')::int = 79 AND category = 'Men';
UPDATE public.products SET brand = 'Yves Saint Laurent' WHERE (specs->>'catalogNo')::int = 111 AND category = 'Men';
UPDATE public.products SET brand = 'Bond No. 9' WHERE (specs->>'catalogNo')::int = 56 AND category = 'Men';
UPDATE public.products SET brand = 'Gucci' WHERE (specs->>'catalogNo')::int = 78 AND category = 'Men';
UPDATE public.products SET brand = 'Louis Vuitton' WHERE (specs->>'catalogNo')::int = 87 AND category = 'Men';
UPDATE public.products SET brand = 'Penhaligon''s' WHERE (specs->>'catalogNo')::int = 94 AND category = 'Men';
UPDATE public.products SET brand = 'Jean Paul Gaultier' WHERE (specs->>'catalogNo')::int = 21 AND category = 'Men';
UPDATE public.products SET brand = 'Ralph Lauren' WHERE (specs->>'catalogNo')::int = 48 AND category = 'Men';
UPDATE public.products SET brand = 'Bond No. 9' WHERE (specs->>'catalogNo')::int = 58 AND category = 'Men';
UPDATE public.products SET brand = 'Rabanne' WHERE (specs->>'catalogNo')::int = 90 AND category = 'Women';
UPDATE public.products SET brand = 'Sol de Janeiro' WHERE (specs->>'catalogNo')::int = 219 AND category = 'Women';
UPDATE public.products SET brand = 'The Body Shop' WHERE (specs->>'catalogNo')::int = 95 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 170 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 222 AND category = 'Women';
UPDATE public.products SET brand = 'Chanel' WHERE (specs->>'catalogNo')::int = 47 AND category = 'Women';
UPDATE public.products SET brand = 'Clinique' WHERE (specs->>'catalogNo')::int = 2 AND category = 'Women';
UPDATE public.products SET brand = 'Jean Paul Gaultier' WHERE (specs->>'catalogNo')::int = 143 AND category = 'Women';
UPDATE public.products SET brand = 'Moschino' WHERE (specs->>'catalogNo')::int = 190 AND category = 'Women';
UPDATE public.products SET brand = 'Rabanne' WHERE (specs->>'catalogNo')::int = 44 AND category = 'Women';
UPDATE public.products SET brand = 'Versace' WHERE (specs->>'catalogNo')::int = 151 AND category = 'Women';
UPDATE public.products SET brand = 'Viktor&Rolf' WHERE (specs->>'catalogNo')::int = 105 AND category = 'Women';
UPDATE public.products SET brand = 'Calvin Klein' WHERE (specs->>'catalogNo')::int = 56 AND category = 'Women';
UPDATE public.products SET brand = 'Givenchy' WHERE (specs->>'catalogNo')::int = 132 AND category = 'Women';
UPDATE public.products SET brand = 'Gucci' WHERE (specs->>'catalogNo')::int = 146 AND category = 'Women';
UPDATE public.products SET brand = 'Louis Vuitton' WHERE (specs->>'catalogNo')::int = 233 AND category = 'Women';
UPDATE public.products SET brand = 'Ralph Lauren' WHERE (specs->>'catalogNo')::int = 14 AND category = 'Women';
UPDATE public.products SET brand = 'Sarah Jessica Parker' WHERE (specs->>'catalogNo')::int = 9 AND category = 'Women';
UPDATE public.products SET brand = 'Yves Saint Laurent' WHERE (specs->>'catalogNo')::int = 130 AND category = 'Women';
UPDATE public.products SET brand = 'Estee Lauder' WHERE (specs->>'catalogNo')::int = 140 AND category = 'Women';
UPDATE public.products SET brand = 'Gucci' WHERE (specs->>'catalogNo')::int = 41 AND category = 'Women';
UPDATE public.products SET brand = 'Hermes' WHERE (specs->>'catalogNo')::int = 112 AND category = 'Women';
UPDATE public.products SET brand = 'Jo Malone London' WHERE (specs->>'catalogNo')::int = 212 AND category = 'Women';
UPDATE public.products SET brand = 'Jo Malone London' WHERE (specs->>'catalogNo')::int = 116 AND category = 'Women';
UPDATE public.products SET brand = 'Louis Vuitton' WHERE (specs->>'catalogNo')::int = 29 AND category = 'Women';
UPDATE public.products SET brand = 'Marc Jacobs' WHERE (specs->>'catalogNo')::int = 148 AND category = 'Women';
UPDATE public.products SET brand = 'The Body Shop' WHERE (specs->>'catalogNo')::int = 87 AND category = 'Women';
UPDATE public.products SET brand = 'Bvlgari' WHERE (specs->>'catalogNo')::int = 3 AND category = 'Women';
UPDATE public.products SET brand = 'DKNY' WHERE (specs->>'catalogNo')::int = 104 AND category = 'Women';
UPDATE public.products SET brand = 'Dolce & Gabbana' WHERE (specs->>'catalogNo')::int = 72 AND category = 'Women';
UPDATE public.products SET brand = 'Jo Malone London' WHERE (specs->>'catalogNo')::int = 113 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 176 AND category = 'Women';
UPDATE public.products SET brand = 'Viktor&Rolf' WHERE (specs->>'catalogNo')::int = 92 AND category = 'Women';
UPDATE public.products SET brand = 'Bath & Body Works' WHERE (specs->>'catalogNo')::int = 215 AND category = 'Women';
UPDATE public.products SET brand = 'Giorgio Armani' WHERE (specs->>'catalogNo')::int = 50 AND category = 'Women';
UPDATE public.products SET brand = 'Jennifer Lopez' WHERE (specs->>'catalogNo')::int = 23 AND category = 'Women';
UPDATE public.products SET brand = 'Narciso Rodriguez' WHERE (specs->>'catalogNo')::int = 184 AND category = 'Women';
UPDATE public.products SET brand = 'Paris Hilton' WHERE (specs->>'catalogNo')::int = 96 AND category = 'Women';
UPDATE public.products SET brand = 'Scarlet' WHERE (specs->>'catalogNo')::int = 183 AND category = 'Women';
UPDATE public.products SET brand = 'The Body Shop' WHERE (specs->>'catalogNo')::int = 22 AND category = 'Women';
UPDATE public.products SET brand = 'Unknown / catalog reference' WHERE (specs->>'catalogNo')::int = 61 AND category = 'Women';
UPDATE public.products SET brand = 'Versace' WHERE (specs->>'catalogNo')::int = 178 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 177 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 80 AND category = 'Women';
UPDATE public.products SET brand = 'Britney Spears' WHERE (specs->>'catalogNo')::int = 133 AND category = 'Women';
UPDATE public.products SET brand = 'Bvlgari' WHERE (specs->>'catalogNo')::int = 117 AND category = 'Women';
UPDATE public.products SET brand = 'Chanel' WHERE (specs->>'catalogNo')::int = 210 AND category = 'Women';
UPDATE public.products SET brand = 'Gucci' WHERE (specs->>'catalogNo')::int = 189 AND category = 'Women';
UPDATE public.products SET brand = 'Ralph Lauren' WHERE (specs->>'catalogNo')::int = 76 AND category = 'Women';
UPDATE public.products SET brand = 'The Body Shop' WHERE (specs->>'catalogNo')::int = 53 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 126 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 162 AND category = 'Women';
UPDATE public.products SET brand = 'Calvin Klein' WHERE (specs->>'catalogNo')::int = 27 AND category = 'Women';
UPDATE public.products SET brand = 'DKNY' WHERE (specs->>'catalogNo')::int = 33 AND category = 'Women';
UPDATE public.products SET brand = 'Prada' WHERE (specs->>'catalogNo')::int = 119 AND category = 'Women';
UPDATE public.products SET brand = 'Guess' WHERE (specs->>'catalogNo')::int = 28 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 89 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 64 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 124 AND category = 'Women';
UPDATE public.products SET brand = 'Anna Sui' WHERE (specs->>'catalogNo')::int = 67 AND category = 'Women';
UPDATE public.products SET brand = 'Ariana Grande' WHERE (specs->>'catalogNo')::int = 150 AND category = 'Women';
UPDATE public.products SET brand = 'Bath & Body Works' WHERE (specs->>'catalogNo')::int = 196 AND category = 'Women';
UPDATE public.products SET brand = 'Bath & Body Works' WHERE (specs->>'catalogNo')::int = 159 AND category = 'Women';
UPDATE public.products SET brand = 'Bath & Body Works' WHERE (specs->>'catalogNo')::int = 17 AND category = 'Women';
UPDATE public.products SET brand = 'Britney Spears' WHERE (specs->>'catalogNo')::int = 8 AND category = 'Women';
UPDATE public.products SET brand = 'Burberry' WHERE (specs->>'catalogNo')::int = 4 AND category = 'Women';
UPDATE public.products SET brand = 'Burberry' WHERE (specs->>'catalogNo')::int = 52 AND category = 'Women';
UPDATE public.products SET brand = 'Chanel' WHERE (specs->>'catalogNo')::int = 138 AND category = 'Women';
UPDATE public.products SET brand = 'Chanel' WHERE (specs->>'catalogNo')::int = 135 AND category = 'Women';
UPDATE public.products SET brand = 'Chanel' WHERE (specs->>'catalogNo')::int = 46 AND category = 'Women';
UPDATE public.products SET brand = 'Christina Aguilera' WHERE (specs->>'catalogNo')::int = 75 AND category = 'Women';
UPDATE public.products SET brand = 'Dior' WHERE (specs->>'catalogNo')::int = 43 AND category = 'Women';
UPDATE public.products SET brand = 'Dolce & Gabbana' WHERE (specs->>'catalogNo')::int = 223 AND category = 'Women';
UPDATE public.products SET brand = 'Dolce & Gabbana' WHERE (specs->>'catalogNo')::int = 153 AND category = 'Women';
UPDATE public.products SET brand = 'Dolce & Gabbana' WHERE (specs->>'catalogNo')::int = 81 AND category = 'Women';
UPDATE public.products SET brand = 'Dunhill' WHERE (specs->>'catalogNo')::int = 141 AND category = 'Women';
UPDATE public.products SET brand = 'Elizabeth Arden' WHERE (specs->>'catalogNo')::int = 45 AND category = 'Women';
UPDATE public.products SET brand = 'Emporio Armani' WHERE (specs->>'catalogNo')::int = 142 AND category = 'Women';
UPDATE public.products SET brand = 'Escada' WHERE (specs->>'catalogNo')::int = 6 AND category = 'Women';
UPDATE public.products SET brand = 'Giorgio Armani' WHERE (specs->>'catalogNo')::int = 194 AND category = 'Women';
UPDATE public.products SET brand = 'Gucci' WHERE (specs->>'catalogNo')::int = 100 AND category = 'Women';
UPDATE public.products SET brand = 'Hugo Boss' WHERE (specs->>'catalogNo')::int = 48 AND category = 'Women';
UPDATE public.products SET brand = 'Juliana Paes' WHERE (specs->>'catalogNo')::int = 118 AND category = 'Women';
UPDATE public.products SET brand = 'Justin Bieber' WHERE (specs->>'catalogNo')::int = 12 AND category = 'Women';
UPDATE public.products SET brand = 'Katy Perry' WHERE (specs->>'catalogNo')::int = 49 AND category = 'Women';
UPDATE public.products SET brand = 'Katy Perry' WHERE (specs->>'catalogNo')::int = 68 AND category = 'Women';
UPDATE public.products SET brand = 'Kayali' WHERE (specs->>'catalogNo')::int = 197 AND category = 'Women';
UPDATE public.products SET brand = 'Kenzo' WHERE (specs->>'catalogNo')::int = 99 AND category = 'Women';
UPDATE public.products SET brand = 'Lancome' WHERE (specs->>'catalogNo')::int = 127 AND category = 'Women';
UPDATE public.products SET brand = 'Lancome' WHERE (specs->>'catalogNo')::int = 79 AND category = 'Women';
UPDATE public.products SET brand = 'Lattafa' WHERE (specs->>'catalogNo')::int = 198 AND category = 'Women';
UPDATE public.products SET brand = 'Lolita Lempicka' WHERE (specs->>'catalogNo')::int = 110 AND category = 'Women';
UPDATE public.products SET brand = 'Nina Ricci' WHERE (specs->>'catalogNo')::int = 123 AND category = 'Women';
UPDATE public.products SET brand = 'Nina Ricci' WHERE (specs->>'catalogNo')::int = 74 AND category = 'Women';
UPDATE public.products SET brand = 'Nishane' WHERE (specs->>'catalogNo')::int = 203 AND category = 'Women';
UPDATE public.products SET brand = 'Parfums de Marly' WHERE (specs->>'catalogNo')::int = 172 AND category = 'Women';
UPDATE public.products SET brand = 'Paris Hilton' WHERE (specs->>'catalogNo')::int = 98 AND category = 'Women';
UPDATE public.products SET brand = 'Playboy' WHERE (specs->>'catalogNo')::int = 185 AND category = 'Women';
UPDATE public.products SET brand = 'Prada' WHERE (specs->>'catalogNo')::int = 195 AND category = 'Women';
UPDATE public.products SET brand = 'Salvatore Ferragamo' WHERE (specs->>'catalogNo')::int = 152 AND category = 'Women';
UPDATE public.products SET brand = 'Selena Gomez' WHERE (specs->>'catalogNo')::int = 34 AND category = 'Women';
UPDATE public.products SET brand = 'Taylor Swift' WHERE (specs->>'catalogNo')::int = 139 AND category = 'Women';
UPDATE public.products SET brand = 'Taylor Swift' WHERE (specs->>'catalogNo')::int = 30 AND category = 'Women';
UPDATE public.products SET brand = 'The Body Shop' WHERE (specs->>'catalogNo')::int = 84 AND category = 'Women';
UPDATE public.products SET brand = 'Valentino' WHERE (specs->>'catalogNo')::int = 232 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 5 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 145 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 122 AND category = 'Women';
UPDATE public.products SET brand = 'Yves Saint Laurent' WHERE (specs->>'catalogNo')::int = 175 AND category = 'Women';
UPDATE public.products SET brand = 'Zara' WHERE (specs->>'catalogNo')::int = 187 AND category = 'Women';
UPDATE public.products SET brand = 'Bath & Body Works' WHERE (specs->>'catalogNo')::int = 36 AND category = 'Women';
UPDATE public.products SET brand = 'Gucci' WHERE (specs->>'catalogNo')::int = 217 AND category = 'Women';
UPDATE public.products SET brand = 'Hugo Boss' WHERE (specs->>'catalogNo')::int = 134 AND category = 'Women';
UPDATE public.products SET brand = 'Kenzo' WHERE (specs->>'catalogNo')::int = 71 AND category = 'Women';
UPDATE public.products SET brand = 'Paris Hilton' WHERE (specs->>'catalogNo')::int = 65 AND category = 'Women';
UPDATE public.products SET brand = 'Tom Ford' WHERE (specs->>'catalogNo')::int = 181 AND category = 'Women';
UPDATE public.products SET brand = 'Versace' WHERE (specs->>'catalogNo')::int = 57 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 169 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 128 AND category = 'Women';
UPDATE public.products SET brand = 'Zara' WHERE (specs->>'catalogNo')::int = 220 AND category = 'Women';
UPDATE public.products SET brand = 'Anna Sui' WHERE (specs->>'catalogNo')::int = 1 AND category = 'Women';
UPDATE public.products SET brand = 'Chloe' WHERE (specs->>'catalogNo')::int = 82 AND category = 'Women';
UPDATE public.products SET brand = 'Dior' WHERE (specs->>'catalogNo')::int = 109 AND category = 'Women';
UPDATE public.products SET brand = 'Escada' WHERE (specs->>'catalogNo')::int = 15 AND category = 'Women';
UPDATE public.products SET brand = 'Estee Lauder' WHERE (specs->>'catalogNo')::int = 88 AND category = 'Women';
UPDATE public.products SET brand = 'Jo Malone London' WHERE (specs->>'catalogNo')::int = 211 AND category = 'Women';
UPDATE public.products SET brand = 'Lanvin' WHERE (specs->>'catalogNo')::int = 93 AND category = 'Women';
UPDATE public.products SET brand = 'Coach' WHERE (specs->>'catalogNo')::int = 226 AND category = 'Women';
UPDATE public.products SET brand = 'DKNY' WHERE (specs->>'catalogNo')::int = 85 AND category = 'Women';
UPDATE public.products SET brand = 'Davidoff' WHERE (specs->>'catalogNo')::int = 91 AND category = 'Women';
UPDATE public.products SET brand = 'Dior' WHERE (specs->>'catalogNo')::int = 206 AND category = 'Women';
UPDATE public.products SET brand = 'Dior' WHERE (specs->>'catalogNo')::int = 201 AND category = 'Women';
UPDATE public.products SET brand = 'Elie Saab' WHERE (specs->>'catalogNo')::int = 58 AND category = 'Women';
UPDATE public.products SET brand = 'Gucci' WHERE (specs->>'catalogNo')::int = 25 AND category = 'Women';
UPDATE public.products SET brand = 'Issey Miyake' WHERE (specs->>'catalogNo')::int = 69 AND category = 'Women';
UPDATE public.products SET brand = 'Rabanne' WHERE (specs->>'catalogNo')::int = 108 AND category = 'Women';
UPDATE public.products SET brand = 'Salvatore Ferragamo' WHERE (specs->>'catalogNo')::int = 78 AND category = 'Women';
UPDATE public.products SET brand = 'The Body Shop' WHERE (specs->>'catalogNo')::int = 60 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 167 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 18 AND category = 'Women';
UPDATE public.products SET brand = 'Cacharel' WHERE (specs->>'catalogNo')::int = 168 AND category = 'Women';
UPDATE public.products SET brand = 'Ex Nihilo' WHERE (specs->>'catalogNo')::int = 173 AND category = 'Women';
UPDATE public.products SET brand = 'Gucci' WHERE (specs->>'catalogNo')::int = 101 AND category = 'Women';
UPDATE public.products SET brand = 'Gucci' WHERE (specs->>'catalogNo')::int = 106 AND category = 'Women';
UPDATE public.products SET brand = 'Katy Perry' WHERE (specs->>'catalogNo')::int = 19 AND category = 'Women';
UPDATE public.products SET brand = 'Kayali' WHERE (specs->>'catalogNo')::int = 205 AND category = 'Women';
UPDATE public.products SET brand = 'One Direction' WHERE (specs->>'catalogNo')::int = 77 AND category = 'Women';
UPDATE public.products SET brand = 'Paris Hilton' WHERE (specs->>'catalogNo')::int = 37 AND category = 'Women';
UPDATE public.products SET brand = 'Britney Spears' WHERE (specs->>'catalogNo')::int = 32 AND category = 'Women';
UPDATE public.products SET brand = 'Britney Spears' WHERE (specs->>'catalogNo')::int = 160 AND category = 'Women';
UPDATE public.products SET brand = 'Dior' WHERE (specs->>'catalogNo')::int = 137 AND category = 'Women';
UPDATE public.products SET brand = 'Giorgio Armani' WHERE (specs->>'catalogNo')::int = 147 AND category = 'Women';
UPDATE public.products SET brand = 'Gucci' WHERE (specs->>'catalogNo')::int = 55 AND category = 'Women';
UPDATE public.products SET brand = 'Lancome' WHERE (specs->>'catalogNo')::int = 40 AND category = 'Women';
UPDATE public.products SET brand = 'Burberry' WHERE (specs->>'catalogNo')::int = 191 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 121 AND category = 'Women';
UPDATE public.products SET brand = 'Amouage' WHERE (specs->>'catalogNo')::int = 225 AND category = 'Women';
UPDATE public.products SET brand = 'Anna Sui' WHERE (specs->>'catalogNo')::int = 188 AND category = 'Women';
UPDATE public.products SET brand = 'Ariana Grande' WHERE (specs->>'catalogNo')::int = 161 AND category = 'Women';
UPDATE public.products SET brand = 'Ariana Grande' WHERE (specs->>'catalogNo')::int = 164 AND category = 'Women';
UPDATE public.products SET brand = 'Ariana Grande' WHERE (specs->>'catalogNo')::int = 193 AND category = 'Women';
UPDATE public.products SET brand = 'Ariana Grande' WHERE (specs->>'catalogNo')::int = 149 AND category = 'Women';
UPDATE public.products SET brand = 'Avril Lavigne' WHERE (specs->>'catalogNo')::int = 26 AND category = 'Women';
UPDATE public.products SET brand = 'Bath & Body Works' WHERE (specs->>'catalogNo')::int = 207 AND category = 'Women';
UPDATE public.products SET brand = 'Bath & Body Works' WHERE (specs->>'catalogNo')::int = 199 AND category = 'Women';
UPDATE public.products SET brand = 'Billie Eilish' WHERE (specs->>'catalogNo')::int = 174 AND category = 'Women';
UPDATE public.products SET brand = 'Carolina Herrera' WHERE (specs->>'catalogNo')::int = 39 AND category = 'Women';
UPDATE public.products SET brand = 'Carolina Herrera' WHERE (specs->>'catalogNo')::int = 38 AND category = 'Women';
UPDATE public.products SET brand = 'Carolina Herrera' WHERE (specs->>'catalogNo')::int = 238 AND category = 'Women';
UPDATE public.products SET brand = 'Carolina Herrera' WHERE (specs->>'catalogNo')::int = 103 AND category = 'Women';
UPDATE public.products SET brand = 'Chanel' WHERE (specs->>'catalogNo')::int = 54 AND category = 'Women';
UPDATE public.products SET brand = 'Chanel' WHERE (specs->>'catalogNo')::int = 154 AND category = 'Women';
UPDATE public.products SET brand = 'Demeter' WHERE (specs->>'catalogNo')::int = 200 AND category = 'Women';
UPDATE public.products SET brand = 'Dior' WHERE (specs->>'catalogNo')::int = 11 AND category = 'Women';
UPDATE public.products SET brand = 'Dior' WHERE (specs->>'catalogNo')::int = 16 AND category = 'Women';
UPDATE public.products SET brand = 'Dolce & Gabbana' WHERE (specs->>'catalogNo')::int = 111 AND category = 'Women';
UPDATE public.products SET brand = 'Jo Malone London' WHERE (specs->>'catalogNo')::int = 221 AND category = 'Women';
UPDATE public.products SET brand = 'Juicy Couture' WHERE (specs->>'catalogNo')::int = 83 AND category = 'Women';
UPDATE public.products SET brand = 'Katy Perry' WHERE (specs->>'catalogNo')::int = 21 AND category = 'Women';
UPDATE public.products SET brand = 'Kayali' WHERE (specs->>'catalogNo')::int = 192 AND category = 'Women';
UPDATE public.products SET brand = 'Kayali' WHERE (specs->>'catalogNo')::int = 204 AND category = 'Women';
UPDATE public.products SET brand = 'Kayali' WHERE (specs->>'catalogNo')::int = 209 AND category = 'Women';
UPDATE public.products SET brand = 'Kilian Paris' WHERE (specs->>'catalogNo')::int = 227 AND category = 'Women';
UPDATE public.products SET brand = 'Kilian Paris' WHERE (specs->>'catalogNo')::int = 224 AND category = 'Women';
UPDATE public.products SET brand = 'Lancome' WHERE (specs->>'catalogNo')::int = 120 AND category = 'Women';
UPDATE public.products SET brand = 'Lancome' WHERE (specs->>'catalogNo')::int = 13 AND category = 'Women';
UPDATE public.products SET brand = 'Lancome' WHERE (specs->>'catalogNo')::int = 155 AND category = 'Women';
UPDATE public.products SET brand = 'Maison Francis Kurkdjian' WHERE (specs->>'catalogNo')::int = 171 AND category = 'Women';
UPDATE public.products SET brand = 'Mugler' WHERE (specs->>'catalogNo')::int = 86 AND category = 'Women';
UPDATE public.products SET brand = 'Paris Hilton' WHERE (specs->>'catalogNo')::int = 163 AND category = 'Women';
UPDATE public.products SET brand = 'Rabanne' WHERE (specs->>'catalogNo')::int = 157 AND category = 'Women';
UPDATE public.products SET brand = 'Selena Gomez' WHERE (specs->>'catalogNo')::int = 20 AND category = 'Women';
UPDATE public.products SET brand = 'Valentino' WHERE (specs->>'catalogNo')::int = 218 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 24 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 156 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 208 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 125 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 115 AND category = 'Women';
UPDATE public.products SET brand = 'Yves Saint Laurent' WHERE (specs->>'catalogNo')::int = 102 AND category = 'Women';
UPDATE public.products SET brand = 'Yves Saint Laurent' WHERE (specs->>'catalogNo')::int = 180 AND category = 'Women';
UPDATE public.products SET brand = 'Hugo Boss' WHERE (specs->>'catalogNo')::int = 214 AND category = 'Women';
UPDATE public.products SET brand = 'Britney Spears' WHERE (specs->>'catalogNo')::int = 63 AND category = 'Women';
UPDATE public.products SET brand = 'Bvlgari' WHERE (specs->>'catalogNo')::int = 107 AND category = 'Women';
UPDATE public.products SET brand = 'Jennifer Lopez' WHERE (specs->>'catalogNo')::int = 97 AND category = 'Women';
UPDATE public.products SET brand = 'Lancome' WHERE (specs->>'catalogNo')::int = 66 AND category = 'Women';
UPDATE public.products SET brand = 'Penhaligon''s' WHERE (specs->>'catalogNo')::int = 216 AND category = 'Women';
UPDATE public.products SET brand = 'Calvin Klein' WHERE (specs->>'catalogNo')::int = 114 AND category = 'Women';
UPDATE public.products SET brand = 'Burberry' WHERE (specs->>'catalogNo')::int = 7 AND category = 'Women';
UPDATE public.products SET brand = 'Jo Malone London' WHERE (specs->>'catalogNo')::int = 165 AND category = 'Women';
UPDATE public.products SET brand = 'Victoria''s Secret' WHERE (specs->>'catalogNo')::int = 144 AND category = 'Women';
UPDATE public.products SET brand = 'Escada' WHERE (specs->>'catalogNo')::int = 62 AND category = 'Women';
UPDATE public.products SET brand = 'Jean Paul Gaultier' WHERE (specs->>'catalogNo')::int = 129 AND category = 'Women';
UPDATE public.products SET brand = 'Louis Vuitton' WHERE (specs->>'catalogNo')::int = 166 AND category = 'Women';
UPDATE public.products SET brand = 'Bath & Body Works' WHERE (specs->>'catalogNo')::int = 35 AND category = 'Women';
UPDATE public.products SET brand = 'Lattafa' WHERE (specs->>'catalogNo')::int = 186 AND category = 'Women';
UPDATE public.products SET brand = 'Mugler' WHERE (specs->>'catalogNo')::int = 213 AND category = 'Women';
UPDATE public.products SET brand = 'Bath & Body Works' WHERE (specs->>'catalogNo')::int = 59 AND category = 'Women';
UPDATE public.products SET brand = 'Burberry' WHERE (specs->>'catalogNo')::int = 94 AND category = 'Women';
UPDATE public.products SET brand = 'Escada' WHERE (specs->>'catalogNo')::int = 31 AND category = 'Women';
UPDATE public.products SET brand = 'Escada' WHERE (specs->>'catalogNo')::int = 136 AND category = 'Women';
UPDATE public.products SET brand = 'Etienne Aigner' WHERE (specs->>'catalogNo')::int = 73 AND category = 'Women';
UPDATE public.products SET brand = 'Hermes' WHERE (specs->>'catalogNo')::int = 158 AND category = 'Women';
UPDATE public.products SET brand = 'Marc Jacobs' WHERE (specs->>'catalogNo')::int = 42 AND category = 'Women';
UPDATE public.products SET brand = 'Miu Miu' WHERE (specs->>'catalogNo')::int = 182 AND category = 'Women';
UPDATE public.products SET brand = 'Salvatore Ferragamo' WHERE (specs->>'catalogNo')::int = 51 AND category = 'Women';
UPDATE public.products SET brand = 'Shakira' WHERE (specs->>'catalogNo')::int = 239 AND category = 'Women';
UPDATE public.products SET brand = 'Davidoff' WHERE (specs->>'catalogNo')::int = 131 AND category = 'Women';
UPDATE public.products SET brand = 'Marc Jacobs' WHERE (specs->>'catalogNo')::int = 179 AND category = 'Women';
UPDATE public.products SET brand = 'Unknown / catalog reference' WHERE (specs->>'catalogNo')::int = 10 AND category = 'Women';

-- Fallback for custom item SZINDORE
UPDATE public.products SET brand = 'Szindore' WHERE id = 'prod-1788452077683' AND (brand IS NULL OR brand = '');

-- 3. Create index for fast brand filtering and searching
CREATE INDEX IF NOT EXISTS idx_products_brand ON public.products(brand);
